max_width = 80
comment_width = 80

format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true

imports_granularity = "Crate"
wrap_comments = true
use_small_heuristics = "Max"
